id: P000277
initial_creation_type: ebook
source_metadata:
  title: ༈ འོད་གསལ་རྫོགས་པ་ཆེན་པོའི་ཁྲེགས་ཆོད་ལྟ་བའི་གླུ་དབྱངས་ས་ལམ་མ་ལུས་མྱུར་དུ་བགྲོད་པའི་རྩལ་ལྡན་མཁའ་ལྡིང་གཤོག་རླབས་ཞིས་བྱ་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  layers:
  - book_title
  - author
  - yigchung
  id: SHE-SHAP-20
web_metadata:
  title:
    en: The Flight of the Garuda That Swiftly Crosses All Paths and Grounds:The Spiritual
      Songs of Dzogchen Trekcho
    bo: འོད་གསལ་རྫོགས་པ་ཆེན་པོའི་ཁྲེགས་ཆོད་ལྟ་བའི་གླུ་དབྱངས་ས་ལམ་མ་ལུས་མྱུར་དུ་བགྲོད་པའི་རྩལ་ལྡན་མཁའ་ལྡིང་གཤོག་རླབས་ཞིས་བྱ་བ་ཞུགས་སོ།
  collection:
    en: Shabkar Series–  Book 20
    bo: ཞབས་དཀར་གསུང་འབུམ།–  དེབ། ༢༠
  author:
    en: Shabkar Tsokdruk Rangdrol
    bo: ཞབས་དཀར་ཚོགས་དྲུག་རང་གྲོལ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-SHAP-20
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-SHAP-20.epub
  description:
    en: ''
    bo: ''
